version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      data-science:
        patterns:
          - "polars*"
          - "marimo*"
          - "pandas*"
          - "numpy*"
      dev-tools:
        patterns:
          - "pytest*"
          - "ruff*"
          - "mypy*"
    labels:
      - "dependencies"
      - "template: maintenance"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
